#!/bin/bash

ISCC_BIN="C:\Programme\Inno Setup 5\ISCC.EXE"
ISS_FILE="//psf/Home/Documents/Development/deepsecurity/$1"
ISS_FILE=${ISS_FILE//\//\\}

VM_NAME="Windows XP"

shift

prlctl resume "$VM_NAME"
prlctl exec "$VM_NAME" $ISCC_BIN $ISS_FILE $*
